#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "*****Running Eslinter with --fix on all TypeScript files******"

# stash staged changes
stash_commit="$(git stash create)"
# reset branch
# git reset —-hard

# Run Eslint on all .ts files
npm run lint -- --fix

status=$?

if [[ -n "${stash_commit}" ]]
then git stash apply "${stash_commit}"
fi

exit $status
