
# Runs Eslint ONLY
# Only when: "Pushing"
# Target branch: any
name: Development
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npx eslint . --ext .ts,.tsx

# Runs Jest and Eslint
# Only on: ["push", "pull_request"] targeting the given branches
# Target branch: "main"
name: Production
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.ts'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # clone latest commit
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npx eslint . --ext .ts,.tsx

    - name: Run Jest
      run: npx jest --passWithNoTests